### ISSUE TITLE
跑起来报错，有三个问题

### ISSUE THREAD

**Issue by mingmars** [zhaoyangpp/LottoProphet#3]
1  要补充导入的包：

**Comment by mingmars** [comment]
torch
torchvision
torchaudio
torchcrf
PyQt5
scikit-learn
joblib
pandas
numpy
requests
beautifulsoup4
loguru
dateutil
pytz
certifi
python-dateutil
threadpoolctl
scipy
lxml

2 报错
我去掉这个参数，可以跳过，但和模型不统一。
self.fc = nn.Linear(hidden_dim, output_dim * output_seq_length)
        self.crf = CRF(output_dim)  # 移除 batch_first 参数

3 训练模型时报错：：
try:
    from model import LstmCRFModel  # 使用绝对导入
except ImportError as e:
    logger.error(f"导入模型类失败: {e}")
    sys.exit(1)


2024-12-22 21:47:20.386 | ERROR    | __main__:<module>:36 - 导入模型类失败: No module named 'model'
改为以下代码可通过，但后面训练失败：
# 获取当前脚本所在的目录
current_dir = os.path.dirname(os.path.abspath(__file__))
# 获取项目根目录
project_root = os.path.abspath(os.path.join(current_dir, '..', '..'))
# 将项目根目录添加到 Python 路径
sys.path.append(project_root)

# 现在可以正常导入 model 模块
from model import LstmCRFModel


4改为后报错：
2024-12-22 21:51:08.295 | INFO     | __main__:<module>:275 - 开始训练模型...
2024-12-22 21:51:08.296 | INFO     | __main__:fetch_data_if_not_exists:119 - 数据文件 g:\python\caipiao\LottoProphet\scripts\dlt\dlt_history.csv 已存在。
2024-12-22 21:51:08.296 | INFO     | __main__:train_model:129 - 加载数据...
2024-12-22 21:51:08.701 | INFO     | __main__:train_model:144 - 使用设备: cuda
2024-12-22 21:51:11.396 | INFO     | __main__:train_model:157 - 开始模型训练...
Traceback (most recent call last):
  File "g:\python\caipiao\LottoProphet\scripts\dlt\train_dlt_model.py", line 276, in <module>
    train_model()
  File "g:\python\caipiao\LottoProphet\scripts\dlt\train_dlt_model.py", line 178, in train_model
    red_loss = red_model(features, red_labels, red_mask)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "g:\python\caipiao\LottoProphet\model.py", line 22, in forward
    loss = -self.crf(logits.view(-1, self.output_dim), tags.view(-1), mask=mask.view(-1) if mask is not None else None, reduction='mean')
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

**Comment by mingmars** [comment]
训练过程中发生异常：'utf-8' codec can't decode byte 0xb5 in position 60: invalid start byte
训练线程已结束。

**Comment by mingmars** [comment]
训练找不到model，改为
project_root = os.path.abspath(os.path.join(current_dir, '..', '..'))

新的问题
![image](https://github.com/user-attachments/assets/3b4f6804-8917-451f-ad1e-86b972de0be7)

**Comment by zhaoyangpp** [comment]
预计明天修复

**Comment by zhaoyangpp** [comment]
修复预测结果重复问题；编码相关问题本地未复现，可能由用户名为中文导致。
